# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :custom_lane do
    # add actions here: https://docs.fastlane.tools/actions

	puts("=====>>> START INSTALL PODS <<<=====")
	cocoapods(
  		repo_update: true,
		use_bundle_exec: false
	)
	puts("=====>>> END INSTALL PODS <<<=====")
	puts("=====>>> START BUILD <<<=====")
	build_app(
		scheme: "CICDTest",
		export_method: "ad-hoc",
		workspace: "CICDTest.xcworkspace"
	)
	puts("=====>>> END BUILD <<<=====")
	puts("=====>>> START SEND BUILD TO CRASHLYTICS <<<=====")
	crashlytics(
    		api_token: "3a4e2329cb90bafda02283273c25decea7cd5e4f",
    		build_secret: "05664ed00561c00aa21331dca241622f0499b7166fc80dfcf260fb3821805115")
	puts("=====>>> END SEND BUILD TO CRASHLYTICS <<<=====")
  end
end
