# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :custom_lane do
    # add actions here: https://docs.fastlane.tools/actions

	puts("=====>>> START INSTALL PODS <<<=====")
	cocoapods(
		use_bundle_exec: false
	)
	puts("=====>>> END INSTALL PODS <<<=====")
	puts("=====>>> START BUILD <<<=====")
	build_app(
		scheme: "CICDTest",
		export_method: "ad-hoc",
		workspace: "CICDTest.xcworkspace"
	)
	puts("=====>>> END BUILD <<<=====")
	puts("=====>>> START SEND BUILD TO CRASHLYTICS <<<=====")
	crashlytics(
    		api_token: "8f051c5ca7e8323d04c34a57f611e3f387ba01d4",
    		build_secret: "b2904ce2382bfe2179e9cc0de0a81cbf352840a7b33bea7510c612b0f0a72d93",
		emails: "mahmoudtarek910@gmail.com", "marwa.aman@vodafone.com", "mahmoud.tarek-abdelzaher@vodafone.com")
	puts("=====>>> END SEND BUILD TO CRASHLYTICS <<<=====")
  end
end
